# Generated by Django 5.0.1 on 2024-02-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ctt.tactic')),
            ],
        ),
    ]
