# Generated by Django 5.0.1 on 2024-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctt', '0002_tacticattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='exercises',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='performance',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
