# Generated by Django 5.0.1 on 2024-02-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctt', '0003_alter_tactic_exercises_alter_tactic_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='PuzzleRun',
        ),
    ]
